
# Change prefix to Ctrl-Space (The conflict-free standard)
unbind C-b
set-option -g prefix C-Space
bind-key C-Space send-prefix

# True color support (Crucial for LazyVim themes)
set -g default-terminal "tmux-256color"
set -ag terminal-overrides ",xterm-256color:Tc"
# Enable mouse support
set -g mouse on

# Fix the famous Vim escape-key delay inside tmux
set -sg escape-time 0

# Smart pane switching with awareness of Vim splits.
bind-key -n C-h run "tmux select-pane -L"
bind-key -n C-j run "tmux select-pane -D"
bind-key -n C-k run "tmux select-pane -U"
bind-key -n C-l run "tmux select-pane -R"

# Smart pane resizing using Meta (Alt) + h/j/k/l
bind-key -n M-h run "tmux resize-pane -L 3"
bind-key -n M-j run "tmux resize-pane -D 3"
bind-key -n M-k run "tmux resize-pane -U 3"
bind-key -n M-l run "tmux resize-pane -R 3"
